import { Trapdestinations } from './trap-destinations';

export const ITEMS: Trapdestinations[] = [
    {
        id: 1,
        destinationName: 'Test1',
        ipAddress: '10.0.0.1',
        portNumber: 81,
        community: "community1",
        status: true,
        version: "V3",
        engine: "v3Id 1",
        v3user: "v3User 1",
        authenticationPassphrase: "v3AutPass test 1",
        authenticationProtocol: "sha"
    },
    {
        id: 2,
        destinationName: 'DestinationName test 2 ',
        ipAddress: '10.0.0.2',
        portNumber: 82,
        community: "community test 2",
        status: false,
        version: "V3",
        engine: "v3Id test 2",
        v3user: "v3User test 2",
        authenticationPassphrase: "v3AutPass test 2",
        authenticationProtocol: "sha",
    },
    {
        id: 3,
        destinationName: 'DestinationName test 3',
        ipAddress: '10.0.0.3',
        portNumber: 83,
        community: "community1",
        status: true,
        version: "V3",
        engine: "v3Id test 3",
        v3user: "v3User test 3",
    },
    {
        id: 4,
        destinationName: 'DestinationName test 4',
        ipAddress: '10.0.0.4',
        portNumber: 84,
        community: "community1",
        status: false,
        version: "V2",
    },
    {
        id: 5,
        destinationName: 'Test2',
        ipAddress: '10.0.0.1',
        portNumber: 81,
        community: "community1",
        status: true,
        version: "V3",
        engine: "v3Id 1",
        v3user: "v3User 1",
        authenticationPassphrase: "v3AutPass test 1",
        authenticationProtocol: "sha"
    },
    {
        id: 6,
        destinationName: 'DestinationName test 3 ',
        ipAddress: '10.0.0.2',
        portNumber: 82,
        community: "community test 2",
        status: false,
        version: "V3",
        engine: "v3Id test 2",
        v3user: "v3User test 2",
        authenticationPassphrase: "v3AutPass test 2",
        authenticationProtocol: "sha",
    },
    {
        id: 7,
        destinationName: 'DestinationName test 4',
        ipAddress: '10.0.0.3',
        portNumber: 83,
        community: "community1",
        status: false,
        version: "V3",
        engine: "v3Id test 3",
        v3user: "v3User test 3",
    },
    {
        id: 8,
        destinationName: 'DestinationName test 5',
        ipAddress: '10.0.0.4',
        portNumber: 84,
        community: "community1",
        status: true,
        version: "V2",
    },
    {
        id: 9,
        destinationName: 'Test3',
        ipAddress: '10.0.0.1',
        portNumber: 81,
        community: "community1",
        status: false,
        version: "V3",
        engine: "v3Id 1",
        v3user: "v3User 1",
        authenticationPassphrase: "v3AutPass test 1",
        authenticationProtocol: "sha"
    },
    {
        id: 10,
        destinationName: 'DestinationName test 7 ',
        ipAddress: '10.0.0.2',
        portNumber: 82,
        community: "community test 2",
        status: true,
        version: "V3",
        engine: "v3Id test 2",
        v3user: "v3User test 2",
        authenticationPassphrase: "v3AutPass test 2",
        authenticationProtocol: "sha",
    },
    {
        id: 11,
        destinationName: 'DestinationName test 8',
        ipAddress: '10.0.0.3',
        portNumber: 83,
        community: "community1",
        status: false,
        version: "V3",
        engine: "v3Id test 3",
        v3user: "v3User test 3",
    },
    {
        id: 12,
        destinationName: 'DestinationName test 9',
        ipAddress: '10.0.0.4',
        portNumber: 84,
        community: "community1",
        status: true,
        version: "V2",
    },
]